---
- hosts: master01
  remote_user: "{{ local_admin }}"
  name: Сборка K8s кластера
  roles:
    - 01-conf_sysctl
    - 02-install_kubernetes
    - 03-add_k8s_cluster
    - role: add_k8s_network
    - role: untain_master
      when: single_node|bool
    - role: install_k8s_nodelocaldns
    - role: install_k8s_provisioners_lvm
      when: lvm_provisioner_namespace == "csi-lvm-system"
    - role: install_k8s_provisioners_lvm_sanlock
      when: lvm_provisioner_namespace == "csi-lvm-system-sanlock"
    - 09-install_k8s_provisioners_nfs
    - 10-install_helm
    - 11-staff_operator_postgres
    - 12-staff_monitoring
    - 13-staff_logging
    - 14-staff_operator_rabbitmq
    - 15-staff_operator_redis

