---

- name: Чтение статуса плагина
  shell: kubectl get pods -n kube-system | grep 'dns'
  register: status_dns
  become: false
  ignore_errors: yes

- name: Создаем локальный сервер DNS
  kubernetes.core.k8s:
    state: present
    force: false
    kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
    definition: "{{ lookup('template', 'node_local_dns.yaml') }}"
  when: status_dns.stdout == ''

...