---

- name: Устанавливаем 'tigera-operator'
  kubernetes.core.k8s:
    state: present
    force: false
    kubeconfig: "/$HOME/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/tigera-operator.yaml') }}"
  when: cni  == "calico"

- name: Устанавливаем 'calico with vxlan'
  kubernetes.core.k8s:
    state: present
    force: false
    kubeconfig: "/$HOME/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/vxlan.yaml') }}"
  when: cni  == "calico"

- name: Устанавливаем 'calico with bgp'
  kubernetes.core.k8s:
    state: present
    force: no
    kubeconfig: "~/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/kube-calico-bgp.yaml') }}"
  when: cni  == "calico_bgp"

- name: Устанавливаем 'flannel'
  kubernetes.core.k8s:
    state: present
    force: no
    kubeconfig: "/$HOME/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/kube-flannel.yml') }}"
  when: cni  == "flannel"

...